version: '3'
services:
  localstack:
    container_name: 'localstack_main'
    image: localstack/localstack
    restart: always
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    environment:
      - DEBUG=true
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_CONTAINER_REGISTRY=mlupin/docker-lambda
    volumes:
      - './localstack_data:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      default:
        aliases:
          - localhost.localstack.cloud
  postgres:
    image: postgres:14.5-alpine3.16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=articles_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - localhost.postgres.db
volumes:
  localstack_data:
  postgres_data:
