service: nestjs-http-api

plugins:
  - serverless-offline
  - serverless-localstack

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  environment: ${file(env.yml):${opt:stage}}

custom:
  localstack:
    stages:
      - local
    host: http://host.docker.internal
    edgePort: 4566

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}

package:
  exclude:
    - node_modules/**
    - test/**
    - prisma/**
    - .devcontainer/**
    - src/**